# Generated by Django 2.2.12 on 2020-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_removed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='static/images/loadingScreen.png', upload_to='imageUploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='static/images/loadingScreen.png', upload_to='imageUploads/'),
        ),
    ]
