# Generated by Django 2.2.12 on 2020-06-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_added_images_2nd_try'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='media/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='media/default.png', upload_to='images/'),
        ),
    ]
