# Generated by Django 2.2.12 on 2020-06-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_added_images_try3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='static/images/loadingScreen.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='static/images/loadingScreen.png', upload_to='images/'),
        ),
    ]
