# Generated by Django 2.2.12 on 2020-07-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_added_images_try5_actually_works_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('phone_number', models.TextField(default='')),
                ('email', models.TextField(default='')),
                ('intro', models.TextField(default='')),
                ('education', models.TextField(default='')),
                ('experience', models.TextField(default='')),
                ('skills', models.TextField(default='')),
                ('interests', models.TextField(default='')),
            ],
        ),
    ]
